# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.cache/wt} [current_project]
set_property parent.project_path {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/CAL_POW.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/F_FRE_POW.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/ad_sub.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/dpll.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/dpll_reset.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/fft_test.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/majority_vote.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/uart_rx_data.v}
  {D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/new/TOP.v}
}
read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci}}
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/mult_gen_1/mult_gen_1_ooc.xdc}}]

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc}}]

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci}}
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_late.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc}}]

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_ooc.xdc}}]

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/ila_0/ila_0.xci}}
set_property used_in_synthesis false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc}}]

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/xfft_0/xfft_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/xfft_0/xfft_0_ooc.xdc}}]

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci}}

read_ip -quiet {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/sources_1/ip/cordic_0/cordic_0.xci}}

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/constrs_1/new/7020.xdc}}
set_property used_in_implementation false [get_files {{D:/a_My_projects/myvivadoprojects/07/23h - 6/fft_test.srcs/constrs_1/new/7020.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
